// Generated by preview/setup-entra-app.ps1 on 2026-05-21T17:32:15.2926127+05:30
// Safe to commit: contains tenant + public client id only (no secrets).
window.ADP_AUTH = {
  clientId: '92cd1e5f-3bdc-470a-8149-9276a6ac0c9d',
  tenantId: '0f14fddf-7d9e-48f3-93b2-9a1d537673f5',
  redirectUri: 'http://127.0.0.1:5500/preview/',
  sharePoint: {
    hostname: 'intelliblend.sharepoint.com',
    sitePath: '/sites/Smartsoft646',
    libraryName: 'Documents'
  },
  copilot: {
    // DirectToEngine 'conversations' URL of the Copilot Studio agent.
    // POST here with a Power Platform delegated bearer token to obtain a
    // DirectLine token + streamUrl that botframework-webchat can consume.
    conversationsUrl: 'https://default0f14fddf7d9e48f393b29a1d537673.f5.environment.api.powerplatform.com/copilotstudio/dataverse-backed/authenticated/bots/crdb4_techComparison/conversations?api-version=2022-03-01-preview',
    title: 'Quote Preparation',
    scopes: ['https://api.powerplatform.com/CopilotStudio.Copilots.Invoke']
  },  scopes: ['User.Read', 'Sites.Read.All', 'Files.Read.All']
};
